[package]
name = "iter_num_tools"
version = "0.2.0"
authors = ["Conrad Ludgate <conradludgate@gmail.com>"]
edition = "2018"
description = "Create simple iterators over non integer ranges. itertools + num = iter_num_tools"
license = "MIT"
readme = "README.md"
repository = "https://github.com/conradludgate/iter-num-tools"
keywords = ["numerics", "mathematics", "iterator"]
categories = ["algorithms", "rust-patterns"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
itertools = "0.10"
